const XLSX = require('xlsx');

const booksData = [
  // Headers
  ['Titulo', 'Autor', 'Paginas', 'Genero', 'Estado', 'Calificacion', 'Notas', 'Fecha_Leido', 'Formato'],
  
  // Data with researched page counts
  ['Alice\'s Adventures in Wonderland', 'Lewis Carroll', 192, 'Literatura', 'Leido', 5, 'Idioma: Inglés', '', 'Fisico'],
  ['Leviathan', 'Thomas Hobbes', 500, 'Filosofia', 'Por leer', 5, 'Idioma: Inglés', '', 'Fisico'],
  ['Meditaciones metafísicas', 'René Descartes', 400, 'Filosofia', 'Por leer', 5, 'Idioma: Latín', '', 'Fisico'],
  ['Discurso del Método', 'René Descartes', 120, 'Filosofia', 'Leido', 4, 'Idioma: Francés', '', 'Fisico'],
  ['Ser y Tiempo', 'Heidegger', 450, 'Filosofia', 'Leido', 5, 'Idioma: Alemán', '', 'Digital'],
  ['The Second Treatise of Civil Government', 'Locke', 200, 'Filosofia', 'Por leer', 5, 'Idioma: Inglés', '', 'Fisico'],
  ['The Social Contract', 'Rousseau', 160, 'Filosofia', 'Por leer', 5, 'Idioma: Francés', '', 'Fisico'],
  ['Discourse on the Origin and Basis of Inequality Among Men', 'Rousseau', 114, 'Filosofia', 'Por leer', 4, 'Idioma: Francés', '', 'Fisico'],
  ['Elements of the Philosophy of Right', 'Hegel', 566, 'Filosofia', 'Por leer', 5, 'Idioma: Alemán', '', 'Digital'],
  ['Crítica de la Razón Pura', 'Kant', 800, 'Filosofia', 'Leido', 5, 'Idioma: Alemán', '', 'Fisico'],
  ['Crítica del Juicio', 'Kant', 343, 'Filosofia', 'Leido', 5, 'Idioma: Alemán', '', 'Digital'],
  ['Textos sobre las razas - Kant (Lerussi y Sanchez Rodriguez)', 'Kant', 250, 'Filosofia', 'Leido', 4, 'Idioma: Alemán', '', 'Fisico'],
  ['El amor en los tiempos del cólera', 'García Márquez', 490, 'Literatura', 'Leido', 3, 'Idioma: Español', '', 'Fisico'],
  ['Crónica de una muerte anunciada', 'García Márquez', 150, 'Literatura', 'Leido', 5, 'Idioma: Español', '', 'Fisico'],
  ['Relato de un náufrago', 'García Márquez', 176, 'Literatura', 'Leido', 4, 'Idioma: Español', '', 'Fisico'],
  ['Rayuela', 'Cortázar', 635, 'Literatura', 'Leido', 4, 'Idioma: Español', '', 'Fisico'],
  ['Libro de Manuel', 'Cortázar', 440, 'Literatura', 'Leido', 3, 'Idioma: Español', '', 'Fisico'],
  ['Octaedro', 'Cortázar', 165, 'Literatura', 'Leido', 3, 'Idioma: Español', '', 'Fisico'],
  ['Bestiario', 'Cortázar', 160, 'Literatura', 'Leido', 3, 'Idioma: Español', '', 'Fisico'],
  ['La Resistencia', 'Sábato', 200, 'Literatura', 'Leido', 1, 'Idioma: Español', '', 'Fisico'],
  ['Uno y el Universo', 'Sábato', 180, 'Literatura', 'Leido', 1, 'Idioma: Español', '', 'Fisico'],
  ['El Túnel', 'Sábato', 185, 'Literatura', 'Leido', 2, 'Idioma: Español', '', 'Fisico'],
  ['Sobre Héroes y Tumbas', 'Sábato', 402, 'Literatura', 'Leido', 2, 'Idioma: Español', '', 'Fisico'],
  ['Abaddón el exterminador', 'Sábato', 350, 'Literatura', 'Leido', 3, 'Idioma: Español', '', 'Fisico'],
  ['Ficciones', 'Borges', 201, 'Literatura', 'Leido', 5, 'Idioma: Español', '', 'Fisico'],
  ['El Aleph', 'Borges', 180, 'Literatura', 'Leido', 5, 'Idioma: Español', '', 'Fisico'],
  ['Dreamtigers', 'Borges', 120, 'Literatura', 'Leido', 4, 'Idioma: Español', '', 'Fisico'],
  ['Three Dialogues Between Hylas and Philonous', 'Berkeley', 150, 'Filosofia', 'Leido', 5, 'Idioma: Inglés', '', 'Fisico'],
  ['The Origin of Species', 'Darwin', 502, 'Filosofia', 'Leido', 4, 'Idioma: Inglés', '', 'Fisico'],
  ['Sun and Steel', 'Mishima', 100, 'Literatura', 'Leido', 4, 'Idioma: Japonés', '', 'Fisico'],
  ['Death in Midsummer (Patriotism)', 'Mishima', 200, 'Literatura', 'Leido', 5, 'Idioma: Japonés', '', 'Fisico'],
  ['Odisea', 'Homero (Fagles, trad)', 541, 'Literatura', 'Leido', 5, 'Idioma: Griego', '', 'Fisico'],
  ['El Quijote', 'Cervantes', 1200, 'Literatura', 'Leido', 5, 'Idioma: Español', '', 'Fisico'],
  ['Der Teil und das Ganze', 'Heisenberg', 285, 'Filosofia', 'Leido', 4, 'Idioma: Alemán', '', 'Fisico'],
  ['Facundo', 'Sarmiento', 280, 'Literatura', 'Leido', 4, 'Idioma: Español', '', 'Fisico'],
  ['El Payador', 'Lugones', 200, 'Literatura', 'Leido', 3, 'Idioma: Español', '', 'Fisico'],
  ['Radiografía de la Pampa', 'Martínez Estrada', 350, 'Literatura', 'Leido', 3, 'Idioma: Español', '', 'Fisico'],
  ['El Mito Gaucho', 'Carlos Astrada', 250, 'Filosofia', 'Leido', 3, 'Idioma: Español', '', 'Fisico'],
  ['Acerca del Alma', 'Aristóteles', 200, 'Filosofia', 'Por leer', 5, 'Idioma: Griego', '', 'Fisico'],
  ['Metafísica', 'Aristóteles', 400, 'Filosofia', 'Por leer', 5, 'Idioma: Griego', '', 'Fisico'],
  ['Gorgias', 'Platón', 150, 'Filosofia', 'Por leer', 0, 'Idioma: Griego', '', 'Fisico'],
  ['Banquete', 'Platón', 120, 'Filosofia', 'Por leer', 0, 'Idioma: Griego', '', 'Fisico'],
  ['Teeteto', 'Platón', 180, 'Filosofia', 'Por leer', 0, 'Idioma: Griego', '', 'Fisico'],
  ['Categorías', 'Aristóteles', 100, 'Filosofia', 'Por leer', 0, 'Idioma: Griego', '', 'Fisico'],
  ['Soumission', 'Houellebecq', 300, 'Literatura', 'Leido', 4, 'Idioma: Francés', '', 'Fisico'],
  ['Heidegger - Escritos tardíos (Bauen, Wohnen, Denken y otros)', 'Heidegger', 350, 'Filosofia', 'Leido', 5, 'Idioma: Alemán', '', 'Fisico'],
  ['El ocaso de los ídolos', 'Nietzsche', 150, 'Filosofia', 'Leido', 4, 'Idioma: Alemán', '', 'Fisico'],
  ['Enquiry concerning human understanding', 'Hume', 200, 'Filosofia', 'Leido', 5, 'Idioma: Inglés', '', 'Fisico'],
  ['El Capital', 'Marx', 900, 'Filosofia', 'Por leer', 4, 'Idioma: Alemán', '', 'Fisico'],
  ['Notes from underground', 'Dostoevsky', 136, 'Literatura', 'Leido', 1, 'Idioma: Ruso', '', 'Fisico'],
  ['Cien años de soledad', 'García Márquez', 471, 'Literatura', 'Leido', 4, 'Idioma: Español', '', 'Fisico'],
  ['1984', 'Orwell', 328, 'Literatura', 'Leido', 4, 'Idioma: Inglés', '', 'Fisico'],
  ['Animal Farm', 'Orwell', 95, 'Literatura', 'Leido', 4, 'Idioma: Inglés', '', 'Fisico'],
  ['Brave New World', 'Huxley', 268, 'Literatura', 'Leido', 3, 'Idioma: Inglés', '', 'Fisico'],
  ['Fahrenheit 451', 'Ray Bradbury', 249, 'Literatura', 'Leido', 3, 'Idioma: Inglés', '', 'Fisico'],
  ['La Metamorfosis', 'Kafka', 96, 'Literatura', 'Por leer', 4, 'Idioma: Alemán', '', 'Fisico'],
  ['5 books of moses y biblia en general', 'Alter (trad)', 1000, 'Literatura', 'Por leer', 0, 'Idioma: Hebreo', '', 'Digital'],
  ['Apología de Sócrates', 'Platón', 80, 'Filosofia', 'Leido', 5, 'Idioma: Griego', '', 'Fisico'],
  ['Heart of Darkness', 'Joseph Conrad', 96, 'Literatura', 'Leido', 4, 'Idioma: Inglés', '', 'Fisico'],
  ['The Charterhouse of Parma', 'Stendhal', 512, 'Literatura', 'Por leer', 3, 'Idioma: Francés', '', 'Fisico'],
  ['The Picture of Dorian Gray', 'Oscar Wilde', 254, 'Literatura', 'Leido', 5, 'Idioma: Inglés', '', 'Fisico'],
  ['Strange case of Dr. Jekyll and Mr. Hyde', 'Stevenson', 96, 'Literatura', 'Leido', 4, 'Idioma: Inglés', '', 'Fisico'],
  ['Lolita', 'Nabokov', 368, 'Literatura', 'Leido', 3, 'Idioma: Inglés', '', 'Fisico'],
  ['Clockwork Orange', 'Anthony Burgess', 192, 'Literatura', 'Leido', 3, 'Idioma: Inglés', '', 'Fisico'],
  ['Das Parfum', 'Süskind', 263, 'Literatura', 'Leido', 3, 'Idioma: Alemán', '', 'Fisico'],
  ['L\'étranger', 'Camus', 123, 'Literatura', 'Leido', 2, 'Idioma: Francés', '', 'Fisico'],
  ['On The Road', 'Kerouac', 320, 'Literatura', 'Leido', 3, 'Idioma: Inglés', '', 'Fisico'],
  ['The Sun also Rises', 'Hemingway', 251, 'Literatura', 'Leido', 3, 'Idioma: Inglés', '', 'Fisico'],
  ['The Old Man and the sea', 'Hemingway', 127, 'Literatura', 'Leido', 3, 'Idioma: Inglés', '', 'Fisico'],
  ['Monadología y Discurso de Metafísica', 'Leibniz', 200, 'Filosofia', 'Leido', 5, 'Idioma: Latín', '', 'Fisico'],
  ['Ética', 'Spinoza', 300, 'Filosofia', 'Por leer', 3, 'Idioma: Latín', '', 'Digital'],
  ['Macbeth', 'Shakespeare', 200, 'Literatura', 'Leido', 5, 'Idioma: Inglés', '', 'Fisico'],
  ['Hávamál', 'Anónimo', 100, 'Literatura', 'Leido', 3, 'Idioma: Nórdico antiguo', '', 'Fisico'],
  ['The Saga of the Volsungs', 'Anónimo', 120, 'Literatura', 'Leido', 3, 'Idioma: Nórdico antiguo', '', 'Fisico'],
  ['Tractatus Logico-Philosophicus', 'Wittgenstein', 75, 'Filosofia', 'Por leer', 5, 'Idioma: Alemán', '', 'Fisico'],
  ['Investigaciones Lógicas', 'Wittgenstein', 400, 'Filosofia', 'Por leer', 4, 'Idioma: Inglés', '', 'Digital'],
  ['Las Obras y los Días - Teogonía', 'Hesiodo', 150, 'Literatura', 'Leido', 5, 'Idioma: Griego', '', 'Fisico'],
  ['Fragmentos presocráticos (Parménides y Heráclito)', 'Varios', 200, 'Filosofia', 'Por leer', 0, 'Idioma: Griego', '', 'Fisico'],
  ['Crimen y Castigo', 'Dostoevsky', 671, 'Literatura', 'Por leer', 4, 'Idioma: Ruso', '', 'Fisico'],
  ['La máquina del tiempo', 'H. G. Wells', 118, 'Literatura', 'Leido', 4, 'Idioma: Inglés', '', 'Fisico'],
  ['Pedro Páramo', 'Juan Rulfo', 124, 'Literatura', 'Por leer', 0, 'Idioma: Español. Releer', '', 'Fisico'],
  ['Niebla', 'Unamuno', 200, 'Literatura', 'Por leer', 0, 'Idioma: Español. Releer', '', 'Digital'],
  ['2666', 'Bolaño', 1125, 'Literatura', 'Leido', 3, 'Idioma: Español', '', 'Fisico'],
  ['Galápagos', 'Vonnegut', 295, 'Literatura', 'Leido', 4, 'Idioma: Inglés', '', 'Fisico'],
  ['Slaughter House 5', 'Vonnegut', 215, 'Literatura', 'Leido', 3, 'Idioma: Inglés', '', 'Fisico'],
  ['Dubliners', 'Joyce', 207, 'Literatura', 'Leido', 3, 'Idioma: Inglés', '', 'Fisico'],
  ['A Portrait of the Artist as a Young Man', 'Joyce', 253, 'Literatura', 'Leido', 3, 'Idioma: Inglés', '', 'Fisico'],
  ['Horla - La Maison Tellier', 'Guy de Maupassant', 150, 'Literatura', 'Leido', 3, 'Idioma: Francés', '', 'Fisico'],
  ['Ab Urbe Condita', 'Tito Livio', 2000, 'Literatura', 'Por leer', 5, 'Idioma: Latín', '', 'Digital'],
  ['El Príncipe', 'Maquiavelo', 128, 'Filosofia', 'Por leer', 3, 'Idioma: Italiano', '', 'Fisico'],
  ['El coronel no tiene quien le escriba', 'García Márquez', 96, 'Literatura', 'Leido', 5, 'Idioma: Español', '', 'Fisico'],
  ['Borges, obras completas vol. 2 (editorial sudamericana)', 'Borges', 500, 'Literatura', 'Leido', 5, 'Idioma: Español', '', 'Fisico'],
  ['El Nombre de la Rosa', 'Eco', 630, 'Literatura', 'Por leer', 4, 'Idioma: Italiano', '', 'Fisico'],
  ['Fear and Loathing in Las Vegas', 'Hunter S. Thompson', 204, 'Literatura', 'Leido', 4, 'Idioma: Inglés', '', 'Fisico'],
  ['La invención de Morel', 'Bioy Casares', 103, 'Literatura', 'Leido', 4, 'Idioma: Español', '', 'Fisico'],
  ['In Cold Blood', 'Truman Capote', 343, 'Literatura', 'Leido', 3, 'Idioma: Inglés', '', 'Fisico'],
  ['Spring Snow', 'Mishima', 389, 'Literatura', 'Por leer', 4, 'Idioma: Japonés', '', 'Digital'],
  ['Botchan', 'Natsume Soseki', 148, 'Literatura', 'Leido', 4, 'Idioma: Japonés', '2025-02-08', 'Digital'],
  ['Anaconda y otros cuentos', 'Quiroga', 200, 'Literatura', 'Leido', 4, 'Idioma: Español', '', 'Fisico'],
  ['Caballos Desbocados', 'Mishima', 421, 'Literatura', 'Leido', 4, 'Idioma: Japonés', '2025-03-07', 'Fisico'],
  ['Templo del Alba', 'Mishima', 350, 'Literatura', 'Por leer', 0, 'Idioma: Japonés', '', 'Fisico'],
  ['Historia del arte', 'Gombrich', 688, 'No ficcion', 'Por leer', 0, 'Idioma: Inglés', '', 'Fisico']
];

// Create worksheet
const worksheet = XLSX.utils.aoa_to_sheet(booksData);

// Create workbook
const workbook = XLSX.utils.book_new();
XLSX.utils.book_append_sheet(workbook, worksheet, 'Biblioteca_Felipe');

// Write to file
XLSX.writeFile(workbook, 'biblioteca_felipe.xlsx');

console.log('Excel creado exitosamente: biblioteca_felipe.xlsx');
console.log(`Total de libros: ${booksData.length - 1}`); // -1 para no contar los headers